### ISSUE TITLE
Product Schematic Typo

### ISSUE THREAD

**Issue by AGlass0fMilk** [sparkfun/Low_Current_Sensor_Breakout-ACS712#1]
In the schematic for the ACS712 breakout (PDF on product page) it says to "Remove C1 for full 80kHz bandwidth." I think this is incorrect and should be changed to say "Remove C5." That capacitor (C5) is on the bandwidth-limiting "Filter" pin of the ACS712.

**Comment by bboyho** [comment]
Hi,

Sorry, I just noticed this comment. I agree since the "Filter" pin on the ACS712 is supposed to adjust the bandwidth.  I'll see what I can do about adjusting the Eagle files and updating the links. I'd also have to update the tutorial that you wrote [ [ACS712 Low Current Sensor Hookup Guide: Hardware Overview](https://learn.sparkfun.com/tutorials/acs712-low-current-sensor-hookup-guide#hardware-overview) ] since it references C1 as the capacitor to remove. I think somehow the labels were rearranged but the note was not updated to reflect the changes.

**Comment by bboyho** [comment]
I checked with the original engineer that designed the board and it looks like the schematic should be correct. He was referring to the capacitor connected to the amplifier in the second stage that is limiting the bandwidth of the output from the ACS712 in the first stage. The ACS712 in the first stage was using the typical application circuit in the datasheet from what he can remember.
